apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

# NO postgres - managed DB. Create orders-db-secret before apply.
resources:
- ../../base/orders-api
- ../../base/orders-web
- ../../base/worker
- ../../base/rbac
- ../../base/networkpolicy
- ingress.yaml
- hpa.yaml
- pdb.yaml

patches:
- target:
    kind: RoleBinding
    name: orders-api
  patch: |-
    - op: add
      path: /subjects/0/namespace
      value: prod
- target:
    kind: RoleBinding
    name: orders-web
  patch: |-
    - op: add
      path: /subjects/0/namespace
      value: prod
- target:
    kind: RoleBinding
    name: worker
  patch: |-
    - op: add
      path: /subjects/0/namespace
      value: prod

# Prod: higher resources, more replicas
- target:
    kind: Deployment
    name: orders-api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "500m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "2"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1Gi"
- target:
    kind: Deployment
    name: orders-web
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"
- target:
    kind: Deployment
    name: worker
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"

commonLabels:
  env: prod
