apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orders-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orders-api
subjects:
- kind: ServiceAccount
  name: orders-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orders-web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orders-web
subjects:
- kind: ServiceAccount
  name: orders-web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: worker
subjects:
- kind: ServiceAccount
  name: worker