apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orders-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orders-web
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: orders-api
            port:
              number: 5000
